-- units 테이블에 분석에 필요한 컬럼 추가
-- DataAnalysis 컴포넌트가 필요로 하는 컬럼들

ALTER TABLE units 
ADD COLUMN IF NOT EXISTS 소유자명 TEXT,
ADD COLUMN IF NOT EXISTS 생년월일 TEXT,
ADD COLUMN IF NOT EXISTS 소유자_주소 TEXT,
ADD COLUMN IF NOT EXISTS 아파트_소재지 TEXT,
ADD COLUMN IF NOT EXISTS 건물명 TEXT,
ADD COLUMN IF NOT EXISTS 거주형태 TEXT,
ADD COLUMN IF NOT EXISTS 등기목적_분류 TEXT,
ADD COLUMN IF NOT EXISTS 근저당금액 NUMERIC,
ADD COLUMN IF NOT EXISTS 보유기간 TEXT,
ADD COLUMN IF NOT EXISTS 압류가압류 TEXT,
ADD COLUMN IF NOT EXISTS 등기원인_년월일 TEXT,
ADD COLUMN IF NOT EXISTS 전용면적_제곱미터 NUMERIC,
ADD COLUMN IF NOT EXISTS 유효근저당총액 NUMERIC,
ADD COLUMN IF NOT EXISTS 압류가압류유무 TEXT,
ADD COLUMN IF NOT EXISTS 주민번호 TEXT,
ADD COLUMN IF NOT EXISTS 연령대 TEXT,
ADD COLUMN IF NOT EXISTS 공유자수 INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS 세대유형 TEXT;

