name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Configure environment
        run: |
          echo "REACT_APP_BASENAME=/${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo "PUBLIC_URL=https://${{ github.actor }}.github.io/${{ github.event.repository.name }}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Export secrets
        run: |
          if [ -n "${{ secrets.REACT_APP_GEMINI_API_KEY }}" ]; then
            echo "REACT_APP_GEMINI_API_KEY=${{ secrets.REACT_APP_GEMINI_API_KEY }}" >> $GITHUB_ENV
            echo "✅ Gemini API key exported"
          else
            echo "⚠️ REACT_APP_GEMINI_API_KEY secret not found; skipping export"
          fi
          
      - name: Install dependencies
        run: npm install
        
      - name: Prepare data (preprocess & copy)
        run: npm run prepare-data

      - name: Build
        run: npm run build
        
      - name: Check build files
        run: |
          echo "Build directory contents:"
          ls -la build/
          echo "Processed data files:"
          ls -la build/processed-data/ || echo "No processed-data directory"
          echo "Processed projects JSON:"
          cat build/processed-projects.json || echo "No processed-projects.json"
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
